### ISSUE TITLE
Has NBuilder stopped being maintained?

### ISSUE THREAD

**Issue by PureKrome** [garethdown44/nbuilder#38]
@garethdown44 Heya - are you there? Has this project stopped being maintained?

if yes - could you open it up to someone else (no, i'm not suggesting me) to be a co-admin so they can take ownership of the outstanding issues, etc.

if no - will you be able to start to adress various issues in the current issue list. (My biggest concern is the #36 ).

**Comment by garethdown44** [comment]
Hi - yeah I don't really have time to look after it anymore and I'd be very happy to open up to a co-admin.

However I will look at #37 today

**Comment by crmckenzie** [comment]
I would be happy to co-admin.

**Comment by PureKrome** [comment]
:wave: @crmckenzie - that would be lovely if you could step up, etc.

.. and then review/etc #36 & #37. :cake:

**Comment by crmckenzie** [comment]
@garethdown44 would you like to chat about co-management?

**Comment by garethdown44** [comment]
@crmckenzie - good to hear from you again! I've given you push rights. We can chat more by email but feel free to get started and let me know if there's anything you need from me. Closing this issue.

**Comment by crmckenzie** [comment]
Hi @garethdown44, when you get a chance could you confirm that you've received my email? Do I still have the correct address?

**Comment by pjmagee** [comment]
@crmckenzie Looking forward to the co-management. It seems like there are some improvements we can make going forward and get some milestones and labels setup for the current issues people have reported but have not been closed or looked into.

**Comment by PureKrome** [comment]
FWIW : I'll be keep an eye on this repo and trying to help out via chatting in issues with suggestions and testing.

We use this product pretty extensively and recently I've started using AutoFac (because of the static/parallel test issues i've been having) but have just felt that the syntax isn't as nice as this and would really love to see some of the issues being worked on (yes, this is OSS which comes with all the things associated to an OSS non-paid voluntary work effort).

:clap: :+1:

**Comment by crmckenzie** [comment]
I've been ill, but I plan on getting things moving really soon. :)
